spring.application.name=ProdReadyFeatures

#DB Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#DevTools Configuration
#spring.devtools.restart.enabled = true
#spring.devtools.restart.exclude = com/springboot/prodreadyfeatures/dto/**

#Server Configuration
server.port = 9000
employeeService.base.url = http://localhost:8080/

#Logging Configuration
logging.level.com.springboot.prodreadyfeatures.clients=trace
logging.level.com.springboot.prodreadyfeatures.config=INFO
logging.pattern.console=%d{dd-mm-yyyy hh:MM:ss} [%level] %c{1.} --- %m%n
logging.file.name=application.log
logging.config=classpath:logback-spring.xml

#Actuator Configuration
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.author=Mansi Arora
info.app.version=1.0.0
management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

#Open API Doc Configuration
springdoc.api-docs.enabled = true
