spring.application.name=ProdReadyFeatures

#DB Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port = 9000

employeeService.base.url = http://localhost:8080/

#Logging Configuration
logging.level.com.springboot.prodreadyfeatures.clients=trace
logging.level.com.springboot.prodreadyfeatures.config=INFO
logging.pattern.console=%d{dd-mm-yyyy hh:MM:ss} [%level] %c{1.} --- %m%n
logging.file.name=application.log
logging.config=classpath:logback-spring.xml